# Copyright Siemens AG, 2014
# SPDX-License-Identifier:	GPL-2.0 LGPL-2.1

# build FOSSology on Travis CI - https://travis-ci.org/

language: c, php

php:
  - 5.3

cache:
 - apt

install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq debhelper libglib2.0-dev libmagic-dev libxml2-dev
        libtext-template-perl librpm-dev  rpm libpcre3-dev libssl-dev
        apache2 libapache2-mod-php5 php5-pgsql php-pear php5-cli php5-sqlite php5-xdebug
        binutils bzip2 cabextract cpio sleuthkit genisoimage poppler-utils
        rpm upx-ucl unrar-free unzip p7zip-full p7zip wget git-core subversion
        postgresql libpq-dev
 - sudo apt-get install -qq cppcheck

before_script:
 - wget http://getcomposer.org/composer.phar
 - php composer.phar install -d src

script:
 - (cd src; vendor/bin/phpunit)
 - make
 - cppcheck -q -isrc/nomos/agent_tests/testdata/NomosTestfiles/ src/

